= Pipeline Global Library for ci.jenkins.io

image:https://ci.jenkins.io/job/Infra/job/pipeline-library/job/master/badge/icon[link="https://ci.jenkins.io/job/Infra/job/pipeline-library/job/master/"]
image:https://img.shields.io/github/v/release/jenkins-infra/pipeline-library[link="https://github.com/jenkins-infra/pipeline-library/releases"]

This repository contains a series of steps and variables for use inside of the
Jenkins project's own link:https://ci.jenkins.io[Jenkins] instance(s).

Check link:https://github.com/jenkins-infra/documentation/blob/master/ci.adoc[this description] of available services.

== Useful steps:

=== buildPlugin

Applies the appropriate defaults for building a Maven-based plugin project on
Linux and Windows.

You are advised to be using a link:https://github.com/jenkinsci/plugin-pom/blob/master/README.md[2.x or newer parent POM].

.Jenkinsfile
[source,groovy]
----
buildPlugin(
  useContainerAgent: true,
  configurations: [
    [platform: 'linux', jdk: 11],
    [platform: 'linux', jdk: 17],
    [platform: 'windows', jdk: 11],
])
----

==== Optional arguments

* `repo` (default: `null`  inherit from Multibranch) - custom Git repository to check out
* `useContainerAgent` (default: `false`) - uses a link:https://github.com/jenkins-infra/documentation/blob/main/ci.adoc#container-agents[Container agent] instead of a Virtual Machine: usually faster to start and generates less costs for the project
** Please note that the implementation of "containers" can be changed over time
* `forkCount` (default: null) - Execute tests with `forkCount` Java virtual machines. Common values include `0.45C`, `1`, `2`, and `1C`.
* `failFast` (default: `true`) - instruct Maven tests to fail fast
* `platforms` (default: `['linux', 'windows']`) - Labels matching platforms to
  execute the steps against in parallel
* `jdkVersions` (default: `[8]`) - JDK version numbers, must match a version
  number jdk tool installed
* `jenkinsVersions`: (default: `[null]`) - a matrix of Jenkins baseline versions to build/test against in parallel (null means default,
  only available for Maven projects)
* `configurations`: An alternative way to specify `platforms`, `jdkVersions` and `jenkinsVersions` (that can not be combined
  with any of them).
* `useArtifactCachingProxy`: (default: `true`) - if set to `false`, artifacts will not use one of the artifact caching proxy depending on the agent provider (Azure, DigitalOcean or AWS), and will directly use repo.jenkins-ci.org instead (discouraged as less reliable and consuming bandwidth)

** Those options will run the build for all combinations of their values. While that is desirable in
  many cases, `configurations` permit to provide a specific combinations of label and java/jenkins versions to use
+
[source,groovy]
----
buildPlugin(/*...*/, configurations: [
  [ platform: "linux", jdk: "11", jenkins: null ],
  [ platform: "windows", jdk: "11", jenkins: null ],
  [ platform: "linux", jdk: "17", jenkins: "2.400" ]
])
----

* `tests`: (default: `null`) - a map of parameters to run tests during the build. The test results and the JaCoCo code
coverage results are recorded after the build with the corresponding Jenkins plugins.
** `skip` - If `true`, skip all the tests by setting the `-skipTests` profile.
  It will also skip FindBugs in modern Plugin POMs.
* `jacoco`: (default: `null`) - a map of parameters to change the default configuration of the `recordCoverage` step of the https://github.com/jenkinsci/code-coverage-api-plugin[Code Coverage Plugin]. This step is called after a plugin build to record the code coverage results of JaCoCo. See https://www.jenkins.io/doc/pipeline/steps/code-coverage-api/#recordcoverage-record-code-coverage-results[recordCoverage step documentation] for a list of available configuration parameters.
* `pit`: (default: `null`) - a map of parameters to change the default configuration of the `recordCoverage` step of the https://github.com/jenkinsci/code-coverage-api-plugin[Code Coverage Plugin]. See https://www.jenkins.io/doc/pipeline/steps/code-coverage-api/#recordcoverage-record-code-coverage-results[recordCoverage step documentation] for a list of available configuration parameters. Since running PIT is a time-consuming task, PIT is disabled by default. You need to enable it by setting the property `skip` to `false` as well.
* `spotbugs`, `checkstyle`, `pmd`, `cpd`: (default: `null`) - a map of parameters to archive SpotBugs, CheckStyle, PMD, or CPD warnings, respectively (only available for Maven projects).
These values can replace or amend the default configuration for the `recordIssues` step of the https://github.com/jenkinsci/warnings-ng-plugin[Warnings NG Plugin].
See https://github.com/jenkinsci/warnings-ng-plugin/blob/master/doc/Documentation.md#configuration[Warnings NG Plugin documentation]
for a list of available configuration parameters.
* `timeout`: (default: `60`) - the number of minutes for build timeout, cannot be bigger than 180, i.e. 3 hours.

NOTE: The `recordIssues` steps of the warnings plugin and the `recordCoverage` steps of the coverage plugin run on the first platform/jdkVersion,jenkinsVersion combination only.
So in the example below it will run for `linux`/`jdk11` but not on `jdk17`.

Usage:

.Jenkinsfile
[source,groovy]
----
buildPlugin(platforms: ['linux'],
        jdkVersions: [11, 17],
        jacoco: [sourceCodeRetention: 'MODIFIED'],
        pit: [skip: false],
        checkstyle: [qualityGates: [[threshold: 1, type: 'NEW', unstable: true]]],
        pmd: [trendChartType: 'TOOLS_ONLY', qualityGates: [[threshold: 1, type: 'NEW', unstable: true]]])
----

=== buildPluginWithGradle()

Builds a Jenkins plugin using Gradle.
The implementation follows the standard build/test/archive pattern.
The method targets compatibility with link:https://github.com/jenkinsci/gradle-jpi-plugin[Gradle JPI Plugin],
and it may not work for other use-cases.

==== Optional arguments

* `repo` (default: `null`  inherit from Multibranch) - custom Git repository to check out
* `failFast` (default: `true`) - instruct the build to fail fast when one of the configurations fail
* `platforms` (default: `['linux', 'windows']`) - Labels matching platforms to
  execute the steps against in parallel
* `jdkVersions` (default: `[8]`) - JDK version numbers, must match a version
  number jdk tool installed
* `configurations`: An alternative way to specify `platforms`, `jdkVersions` (that can not be combined
  with any of them)
** Those options will run the build for all combinations of their values. While that is desirable in
  many cases, `configurations` permit to provide a specific combinations of label and java/jenkins versions to use
+
[source,groovy]
----
buildPluginWithGradle(/*...*/, configurations: [
  [ platform: "linux", jdk: "8" ],
  [ platform: "windows", jdk: "8"],
])
----

* `tests`: (default: `null`) - a map of parameters to run tests during the build
** `skip` - If `true`, skip all the tests.
* `jacoco`: (default: `null`) - a map of parameters to change the default configuration of the `recordCoverage` step of the https://github.com/jenkinsci/code-coverage-api-plugin[Code Coverage Plugin]. This step is called after a plugin build to record the code coverage results of JaCoCo. See https://www.jenkins.io/doc/pipeline/steps/code-coverage-api/#recordcoverage-record-code-coverage-results[recordCoverage step documentation] for a list of available configuration parameters.
* `spotbugs`, `checkstyle`: (default: `null`) - a map of parameters to archive SpotBugs or CheckStyle warnings, respectively.
These values can replace or amend the default configuration for the `recordIssues` step of the https://github.com/jenkinsci/warnings-ng-plugin[Warnings NG Plugin].
See https://github.com/jenkinsci/warnings-ng-plugin/blob/master/doc/Documentation.md#configuration[Warnings NG Plugin documentation]
for a list of available configuration parameters.
* `timeout`: (default: `60`) - the number of minutes for build timeout, cannot be bigger than 180, i.e. 3 hours.
* `noIncrementals`: (default: `false`) - de-activates incremental version publication.

==== Limitations

Not all features of `buildPlugin()` for Maven are supported in the gradle flow.
Examples of not supported features:

* Configuring `jenkinsVersion` for the build flow (as standalone arguments or as `configurations`)
* Usage of link:https://azure.microsoft.com/en-us/services/container-instances/[Azure Container Instances] as agents (only Maven agents are configured)

=== infra.isTrusted()

Determine whether the Pipeline is executing in an internal "trusted" Jenkins
environment

.Jenkinsfile
[source,groovy]
----
if (infra.isTrusted()) {
    /* perform some trusted action like a deployment */
}
----

=== infra.ensureInNode(nodeLabels, body)

Ensures that the given code block is runs in a node with the specified labels

.Jenkinsfile
[source,groovy]
----
infra.ensureInNode('docker,java') {
    sh 'docker -v'
}
----

=== runBenchmarks

Runs JMH benchmarks and archives benchmark reports on `highmem` nodes.

Supported parameters:

`artifacts`::
(Optional) If `artifacts` is not null, invokes `archiveArtifacts` with the given string value.


==== Example

[source, groovy]
----
runBenchmarks('jmh-report.json')
----

=== buildDockerAndPublishImage(imageName, config)

Lints, Builds, then publishes a docker image.

Adds a bunch of build args you can use in your docker image:

* GIT_COMMIT_REV - The commit that triggered this build
* GIT_SCM_URL - Url to repo
* BUILD_DATE - Date that the image was built (now)

Supported parameters:

`imageName`::
Name of the docker image to build

`configs`::
(Optional) extra flags

registry: override the smart default of jenkinsciinfra/ or jenkins4eval/
dockerfile: override the default dockerfile of Dockerfile

==== Example
[source, groovy]
----
buildDockerImage_k8s('plugins-site-api')
----

== Contribute

=== Requirements

* (Open)JDK v8
* Maven 3.6.x

===
