---
name: Bump `docker-helmfile` version

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastVersion:
    kind: githubrelease
    name: Get the latest updatecli version
    spec:
      owner: "jenkins-infra"
      repository: "docker-helmfile"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      versionfilter:
        kind: semver
    transformers:
      - trimprefix: v

conditions:
  checkIfDockerImageIsPublished:
    name: "Check if the Docker Image is published"
    kind: dockerimage
    spec:
      image: "jenkinsciinfra/helmfile"
      architecture: amd64

targets:
  updateGroovyCode:
    name: Update docker-helmfile in groovy code
    kind: file
    spec:
      file: vars/updatecli.groovy
      # Please note that the patterns are specified as "block scalars" (>) with the last endline trimmed (-) to avoid tedious escaping of simple quotes
      matchpattern: >-
        'jenkinsciinfra/helmfile:(.*)'
      replacepattern: >-
        'jenkinsciinfra/helmfile:{{ source `lastVersion` }}'
    scmid: default
  updateDoc:
    name: Update docker-helmfile in documentation
    kind: file
    spec:
      file: vars/updatecli.txt
      matchpattern: jenkinsciinfra/helmfile:(\d+\.\d+\.\d+)\"
      replacepattern: jenkinsciinfra/helmfile:{{ source `lastVersion` }}"
    scmid: default

pullrequests:
  default:
    kind: github
    title: Bump `docker-helmfile` version to {{ source "lastVersion" }}
    scmid: default
    spec:
      labels:
        - dependencies
        - jenkinsciinfra/helmfile
