---
title: "Bump docker-helmfile version on shared library resources"
sources:
  lastVersion:
    kind: githubRelease
    name: Get the latest updatecli version
    spec:
      owner: "jenkins-infra"
      repository: "docker-helmfile"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      versionFilter:
        kind: latest

conditions:
  checkIfDockerImageIsPublished:
    name: "Check if the Docker Image is published"
    kind: dockerImage
    spec:
      image: "jenkinsciinfra/helmfile"

targets:
  updateGroovyCode:
    name: Update docker-helmfile in groovy code
    kind: file
    spec:
      file: vars/updatecli.groovy
      # Please note that the patterns are specified as "block scalars" (>) with the last endline trimed (-) to avoid tedious escaping of simple quotes
      matchpattern: >-
        'jenkinsciinfra/helmfile:(.*)'
      replacepattern: >-
        'jenkinsciinfra/helmfile:{{ source `lastVersion` }}'
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
  updateDoc:
    name: Update docker-helmfile in documentation
    kind: file
    spec:
      file: vars/updatecli.txt
      matchpattern: jenkinsciinfra/helmfile:(\d\.\d\.\d)
      replacepattern: jenkinsciinfra/helmfile:{{ source `lastVersion` }}
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
